### ISSUE TITLE
 [stable/locust] Using an Ingress with the v0.9.10 returns 404

### ISSUE THREAD

**Issue by recfab** [deliveryhero/helm-charts#128]
Hello,

I'm installing this chart on one of our clusters. Unfortunately, when enabling the ingress the ingress controller returns the standard NGINX 404 Not Found error page, rather than routing correctly to the service. Removing the asterisk from the path fixes it. I was hoping there was an `ingress.hosts[].path` variable I could set in the values file, but it is hardcoded in the template.

The path was changed from `/` to `/*` in #127, and I see it was changed in order to fix a bug related to static files.  

I'm pretty new to helm and I'm not sure if this is a problem with the chart or with the cluster. We definitely have used asterisks in paths before, on other clusters. This cluster is new to me, but the thing I know is different from the others is that it has 2 Ingress Controllers. (I also had to set the `kubernetes.io/ingress.class` annotation for it to work at all.)

For now, I can just install v0.9.9 and it works fine. But I was hoping it could be made configurable, or perhaps just provide some pointers to determine whether it's a cluster problem.

If you decide to make it configurable, I'm happy to submit a PR. 

Please let me know if you need additional information.

Thank you.

**Comment by linzhengen** [comment]
I'm using an EKS Cluster and [AWS load balancer controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller), so I need to set the `/*` path.
It seems to be a problem due to environmental differences.

> But I was hoping it could be made configurable

I think this way is better.

locust/templates/master-ingress.yaml
```yml
...
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          # configurable
          - path: {{ .path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: 8089
    {{- end }}
...
```
