### ISSUE TITLE
[cluster-overprovisioner] Helm chart doesn't honor namespace

### ISSUE THREAD

**Issue by Ghazgkull** [deliveryhero/helm-charts#216]
The cluster-overprovisioner helm chart doesn't honor the namespace passed in to helm. This is because the chart is missing the typical metadata configuration on its kubernetes resources.

To reproduce this problem:
1. `helm fetch deliveryhero/cluster-overprovisioner --version 0.7.2 --untar=true`
2. `helm template my-release cluster-overprovisioner --namespace overprovisioner  > cluster-overprovisioner.yaml`
3. Inspect the manifests output to the cluster-overprovisioner.yaml file. Note that none of them are configured to use the "overprovisioner" namespace passed to helm in step 2.

The fix for this is pretty simple. This chart's resources should be configured to honor the Helm release namespace. Like so:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $fullname }}-{{ .name }}"
  namespace: {{ .Release.Namespace }}
  ...
```
