### ISSUE TITLE
[Node-problem-detector] helm template --namespace <NAMESPACE> does not set metadata.namespace on daemonset resource yaml

### ISSUE THREAD

**Issue by rajaSahil** [deliveryhero/helm-charts#240]
### Issue
I'm using the `helm template` command to generate the resource yamls for node-problem-detector. 
But `helm template --namespace <NAMESPACE> ...` does not set **metadata.namespace** field on the daemonset yaml due to which daemonset pods are getting installed in the default namespace.

To reproduce the issue:
```
1.  helm repo add deliveryhero https://charts.deliveryhero.io/ && helm fetch deliveryhero/node-problem-detector --untar=true
2. cd node-problem-detector/
3. helm template npd . --namespace npd > node-problem-detector.yaml
4. Inspect the manifests. Daemonset yaml doesn't have a namespace field
```
#### Reason

- This is because the daemonset template yaml is missing metadata.namespace configuration field. 

### FIX
To fix this, we just need to add the metadata.namespace configuration field in the resource yaml.

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "node-problem-detector.fullname" . }}
  namespace: {{ .Release.Namespace }}
 . . .
```
