### ISSUE TITLE
[stable/locust]: failure to install when auth is enabled 

### ISSUE THREAD

**Issue by PiyushBhatewara** [deliveryhero/helm-charts#244]
Locust chart version: 0.20.2 
When auth is enabled by - 

```
master:
  auth:
    enabled: true
    username: "abc"
    password: "abc"
```
we are getting an error 
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].args[1]): invalid type for io.k8s.api.core
.v1.Container.args: got "map", expected "string"
```

@yosri2005
