### ISSUE TITLE
[node-problem-detector] Should mount /dev/kmsg by default

### ISSUE THREAD

**Issue by L1ghtman2k** [deliveryhero/helm-charts#276]
kernel-monitor.json references /dev/kmsg:
https://github.com/kubernetes/node-problem-detector/blob/e7fe0b20dc8279130d41218d12802d85d6730728/config/kernel-monitor.json#L3

However, it is not mounted by default to the container.

Our workaround is to add the following to values.yaml:
```
extraVolumes:
  - name: kmsg
    hostPath:
      path: /dev/kmsg

extraVolumeMounts:
  - name: kmsg
    mountPath: /dev/kmsg
    readOnly: true
 ```
