### ISSUE TITLE
Distribute workers evenly across nodes

### ISSUE THREAD

**Issue by sstewart-hirez** [deliveryhero/helm-charts#321]
Hi there I am testing with cluster that starts with 100 nodes and with 200 workers. I noticed the workers do not evenly distribute across the nodes so I made change below to work deployment's template.spec. What do you think about incorporating this change as a parameter like worker.topologySpreadConstraints.enabled with default value false?

```
worker-deployment.yaml 
spec:
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              type: worker
```
