### ISSUE TITLE
locust: installing extensions?

### ISSUE THREAD

**Issue by oxr463** [deliveryhero/helm-charts#345]
Reference(s):
- https://github.com/SvenskaSpel/locust-plugins

**Comment by donis88** [comment]
@oxr463 
In my case...
my own image is not working

```
# Dockerfile
FROM locustio/locust:2.8.6
RUN pip3 install grpcio
RUN pip3 install grpcio-tools

COPY . /home/locust/.
```


```
# values.yaml
loadtest:
  name: grpc-loadtest
master:
  image: locust-grpc:0.0.1
worker:
  image: locust-grpc:0.0.1
  hpa:
    enabled: true
    minReplicas: 5
```


helm upgrade --install locust deliveryhero/locust -f values.yaml

but just **CrashLoopBackOff**
master pod logs is 
`exec /bin/sh: exec format error`

can you help me?
