### ISSUE TITLE
locust issue with pip installed packages

### ISSUE THREAD

**Issue by akuzni2** [deliveryhero/helm-charts#356]
values file
```
loadtest:
  name: example
  locust_locustfile: main.py
  locust_locustfile_path: "/mnt/locust"
  locust_locustfile_configmap: "my-loadtest-locustfile"
  locust_lib_configmap: "my-loadtest-lib"
  locust_host: https://www.google.com
  pip_packages:
    - boto3
  headless: false
executed
  excludeTags: ""
  locustCmd: "/opt/venv/bin/locust"

image:
  repository: locustio/locust
  tag: 2.8.6
```

doing 
```
helm upgrade --install example deliveryhero/locust --values example.yaml
```

logs

```
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```
