### ISSUE TITLE
[stable/cachet:1.3.1] Duplicated definition of DB_DRIVER env variable

### ISSUE THREAD

**Issue by cezaryulita** [deliveryhero/helm-charts#385]
Having configmap.yaml defined as
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cachet.fullname" . }}
  labels:
{{ include "cachet.labels" . | indent 4 }}
data:
  # database
  DB_HOST: {{ .Values.database.host  }}
  DB_DATABASE: {{ .Values.database.name  }}
  DB_USERNAME: {{ .Values.database.username }}
  DB_DRIVER: {{ .Values.database.driver }}
  DB_PORT: {{ .Values.database.port | quote }}
  APP_ENV: {{ default "production" .Values.env.APP_ENV | quote }}
  APP_URL: {{ .Values.ingress.host }}
  {{- range $key, $value := .Values.env.public }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
```
effectively results in release being undeployable by rendering output as
```
data:
  # database
  DB_HOST: cachet-db.example.com
  DB_DATABASE: cachet
  DB_USERNAME: cachet
  DB_DRIVER: pssql
  DB_PORT: "5432"
  APP_ENV: "production"
  APP_URL: chart-example.local
  APP_DEBUG: "false"
  APP_LOG: "errorlog"
  CACHET_BEACON: "false"
  CACHET_EMOJI: "false"
  CACHE_DRIVER: "database"
  DB_DRIVER: "pgsql"
```
that causes:
Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 28: mapping key "DB_DRIVER" already defined at line 19
