### ISSUE TITLE
[Kube Downscaler] Create config block and use ConfigMap for it

### ISSUE THREAD

**Issue by fedaykin-b** [deliveryhero/helm-charts#582]
Hi, 

I discovered your Kube Downscaler chart recently and decided to use it. 

I'd like to propose something like shown below for configuring downscaler, instead of relying in raw definition of keys in `env` block:

```yaml
# values.yaml

config:
  # default empty values to avoid impact in a installations and be backward compatible with previous usage of env block
  defaultUptime: ""
  defaultDowntime: ""
  dowscalePeriod: ""
  namespace:
    activeIn: ""
    inactiveIn: ""
```
the fields `namespace.activeIn` and `namespace.inactiveIn` are inspired in this helm-chart: https://github.com/hahow/kube-downscaler, I found it easy to understand. Those values would be read from a ConfigMap and used in the deployment.

If you approve this idea, I can make a PR.
